### ISSUE TITLE
Compare and align with NKAmapper's script

### ISSUE THREAD

**Issue by NKAmapper** [atorger/nvdb2osm#10]
I think your project is going to be very important for OSM in Sweden, so I am going to bother you a little more with a few observations. Here are some ideas, just for consideration, regarding tagging of the main highway categories. It will produce a nice hierarchy on the map according to importance. [Examples in this folder](https://www.jottacloud.com/s/0592631d082283b49939bb929c3050af021), also including the script which generated it (an earlier attempt to use the Homogeniserad format from Lastkajen, but it proved to contain too little information).

My comments are based on the file which you made available early on (Göteborg), which is likely outdated already. Also, you may have more information available in shape files which is not present in Homogeniserad. 

1) Trunk/primary/secondary
Sweden OSM has very strange guidelines for how to tag these categories, unlike anything else I have seen in Europe. A lot of personal judgement seems to be needed to get the tagging right (if that can even be concluded). This is also a question of what the "default" suggestion ought to be, since the final tagging at import tends to be skewed (quite heavily) towards the readily available default in the file. On this background it could be better to stick to the official highway categories and tag correspondingly for the generated file, and then let the user who is importing make the necessary changes for OSM. That produce a map similar to what Trafikverket and Lantmäteriet are making. Tagging would be trunk for category 1 and 2, primary for category 3 and secondary for category 4 (plus additions of motorway and motorroad as applicable).

2) Tertiary
Remaining roads with functional road class < 6.

3) Unclassified/residential/service
- Residential if the road has a private maintainer (väghållar) and the area is market as urban (tättbebyggt) and either the functional road class < 9, or the road has been given a road number (in which case it is regarded as an "allmänn" road, which fits well with the distinction between service and residential/unclassified)
- Unclassified if all of the above, but not an urban area
- Service for the remaining private maintainer roads
- Residential if the road maintainer is not private (seems to be municipality roads in urban areas)

4) Links (moroway_link, trunk_link, primary_link etc)
I do not know if you have specific information available about ramps/links. Here is one indirect way to identify roads for the "_link" tag in Homogeniserad: Put it on the roads matching all of the following criteria:
- Either motorway, trunk or primary (as defined above)
- "Leveranskvalitetsklasse" < 4 (for maintainance/underhål/DoU 2017)
- Exclude roundabouts

**Comment by anders-xarepo** [comment]
Regarding highway tagging I've been recommended by prominent members in community to keep whatever is in there before, and indeed it's up to personal judgement, this means that what comes out of the script is generally not used.

This is for trunk/primary/secondary and tertiary. The script often agrees with the previous value, but not always, and then I've used whatever value that is already mapped, unless it's obviously incorrect.

One problem is that functional road class in NVDB is a mix between road importance and road quality. It should according to spec really only be about road importance, but for smaller roads quality is a factor. For the OSM tagging in Sweden I've been told that road importance should be the sole factor, not road quality. Another problem is that functional road class exist in more than one layer and they don't agree. Currently the script uses a mix of the layers to try come up with something that usually match the pre-existing classification.

On small roads, Lantmäteriet raster map has more information on the roads than NVDB has. Differing between unclassified and track is not really possible. There is a default, which generally turns out to be a road quality rather than road importance, meaning that a newly built but unimportant forestry road becomes unclassified, and and often used small link road can become a track. This must be resolved manually. Likewise if one want to specify quality like the Lantmäteriet raster map, one have to manually specify tracktype, functional road class doesn't work for this.

service roads are also not possible to resolve from NVDB.

Etc.

One can adjust the current translation if one want, but it won't make much of a difference as you will have to verify and adjust the highway type often regardless.

**Comment by atorger** [comment]
Oh, I was signed in as my work user... multiple github users is a mess. Anyway, I think 100% of roads down to tertiary is already existing, so I think it's unlikely that these will be changed from the previous value unless someone knows what they are doing.

The cases where the defaults may slip in is on new roads as JOSM validator does not inform about pre-existing roads then that makes you take a look. In my mapping experience so far is for tiny roads and residential. Unfortunately there's not that much information there, so the script cannot do that much. See the resolve_highways() function in process_and_resolve.py where most of this is done.

If residential, service, unclassified and track could be resolved reliably that would be a win for new roads, but the information is not there. Arguably, residential info is there, but certainly not for proper distinction between unclassified, service and track.

In my own mapping using this script I haven't found this to be a big problem though, changing the highway tag is a very quick thing to do compared to merging the geometry.

**Comment by NKAmapper** [comment]
After having done hundreds of highway imports I can safely say that it does matters how the default tagging is done in the import files. Even for existing roads, most of the highways in OSM will be swapped with the new ones because of the offset for the existing roads, and because it is the most efficient way of getting maxspeed, street name etc right. And because of the uneven quality in OSM, combine with the scope of the job (millions of highway segments), there is an observable tendency for importers to chose the tagging from the import files.

Anyway, I think it would be good to let the local community review and comment on the tagging proposal in example files as a first step in an import review process.

A quick note on highway=track: NVDB is supposed to contain only highways for cars, trucks etc, so it is not supposed to have any "track" type roads at all. It contains "skogsbilväg" for trucks, but not "skogsväg" for tractors, forestry machinery etc. However some of these roads have fallen into decay and needs to be manually retagged to track.
https://www.biometria.se/wp-content/uploads/2019/11/Klassning-av-skogsbilvägar_fickformat_webb.pdf

**Comment by atorger** [comment]
Using "track" for less important skogsbilväg is common practice in rural Sweden for a very long time, so I don't think we can change that now. Tracks that are so bad that it's not suitable for cars to use them is then instead marked with tracktype grade4 or grade5. NVDB does not provide enough information to make any of these distinctions though.

Unfortunately the skogsbilvägar-klassning document is a theory that is not that well applied. Skogsbilvägar is as far as I understand reported mostly by the forestry companies, and they don't have as strict classification as Trafikverket has for the government maintained roads, and possibly also different forest companies make different types of reports. In practice the forestry roads are classified in a mix between how new they are (ie quality) and their importance. Manual adjustment (usually downgrading) is required for a good result. On top of that there are privately owned roads not reported by any forestry company that can have yet another interpretation of the class.

Simply put - it's not possible, as the data is not there.

Likewise, there's a tradition here in Sweden to make roads going to individual houses as highway=service. That information does not exist in NVDB, there's no information that says that a road goes to a house, but you can see it on the map. In the mountains with lots of leisure housing changing roads to service is very common task. In cities there's residential roads, so there there is no problem.

For trunk/primary/secondary/tertiary getting it straight from NVDB could work, but it wouldn't always match what's in OSM now. One can possible tune translation further to make it match more often I have noted that I need to downgrade quite often (currently the script uses an extra layer for functional road class thtat may upgrade roads compared to just using one layer, it worked better in initial tests, but the more I have worked with it, it seems like the older would match more often).

I have discussed highway tagging this in the Swedish community and I have observed that just discussing the idea of replacing with a preset from NVDB will make traditionalists upset. Auto-replacing stuff without traditional manual judgement is a recipe for conflict in the community.

While I'm all for making the defaults as good as possible, they already aim to be that. I can surely adjust them if an improvement is found, but the core problem cannot be solved -- there is not enough data to make a choice that can be imported straight away without need for manual judgement.

I always say to people that want to use the script that they need to merge manually and responsibly, and see it as a tool to map faster manually, and not just a straight import. While one cannot guarantee that people start misusing the script, the only real alternative is to not publish it at all, as something that is ready for straight import without post-processing is not possible if one want the best result.

I have so far imported three full kommuner for myself, and has started with the fourth. I have talked openly about my work, and my method is accepted, even by traditionalists. I work with the replace geometry tool, cutting up segment for segment to not loose any original tags or relations or history, and manually adjust conflicts. It's plenty work, say 60 hours for a kommun, and there are 290 kommuner in Sweden, so say ~20000 man-hours to go through everything. My goal will be to map mainly the kommuner I have personal interest in. I personally don't really have a plan to go through all of Sweden.

**Comment by atorger** [comment]
To summarize, I agree with the goal that the script should make as good defaults as possible. Currently I don't see any improvement that can be made though, except possibly for trunk/primary/secondary which I may adjust.

It's not really worthwhile to just read the Trafikverket specs and make a theory from that, one need to test it on the actual data. There is now a translation function in process_and_resolve.py for this, and to make changes specific references into that and what should be changed is probably better than generic discussion.

And of course, the thing is that regardless how we do it, manual adjustment will be necessary for best results. If someone misuses the script and just delete existing data and replace it with the script output without adjustment or true merging work, I'll be the first to report it as vandalism.

**Comment by NKAmapper** [comment]
I think my three example files show that it is in fact possible to have sensible defaults for tertiary/unclassified/residential/service based on data which is already in NVDB.

For trunk/primary/secondary it is more a question of what is the easiest to relate to for the importer, since manual changes are going to be made anyway.

**Comment by atorger** [comment]
Your script and mine does about the same thing, and they use the same input information. I don't import railway crossings yet though (excluded all railway data), I'll add an issue for that. When I get time I could go a bit more in detail in your script and see what differs.

I work so far mostly on rural areas, and there information is clearly lacking, and skogsbilvägar classification is not that good. For cities and large roads are quite fine.

**Comment by atorger** [comment]
Changed the title to what I think the task is, ie looking through your script and see what it does and compare to mine and see if there are things to adjust. It's quite a lot of work though and I'm supposed to be working on a different project now, so we'll see when I get time. Specific (small) patch suggestions are otherwise welcome, but rather not large patches that changes a lot at once.

**Comment by NKAmapper** [comment]
FYI, I have uploaded a revised version of the script with more readable nvdb attribute names, and also two more rural municipalities.

**Comment by NKAmapper** [comment]
I moved the script (for Sweden) here: https://github.com/NKAmapper/nvdb2osm

**Comment by atorger** [comment]
I have now made a minor adjustment to highway mapping, where both KLASS 8 and 9 gets mapped to track, before KLASS 8 was mapped to unclassified. The reason is that overall it seems like there is considerable less need of adjusting, and it's probably better needing to upgrade than to downgrade, as I think if there is wrong tagging it's better if it's too low a class than too high.

My script uses Funktionell vägklass (KLASS) as a fallback when there is no other information. The table is like this:
0, 1 => trunk
2 => primary
3, 4 => secondary
5, 6 => tertiary
7 => unclassified
8, 9 => track

Residential is not in there as they are already resolved by other layers (they are usually KLASS 7)

We need to sort the mapping of unclassified, service and track, our scripts have major differences there. Other things are more minor. Looking at Lycksele.osm as example. Your script makes the following (outside residential)

7, 8 => unclassified
9 => service

You also look at väghållare enskild. According to my investigations using väghållare layer is redundant though so my script doesn't load that layer. All 7, 8, 9 is enskild outside residential, and if in residential (kommunal väghållare) the layer Gatutyp is active and gives richer information. I'm quite sure if you use all other road information and use KLASS last, you'll notice that väghållare does not add any resolvable information.

As far as I understand the reason for the different conversions is that we use different definitions of what service/track/unclassified should be, ie we both think our own script does the right thing as we have a different view of how these roads should be mapped.

This is the definition I use when mapping:

Unclassified should only be used for more important small roads, that actually leads somewhere or connects larger roads, and not just to a forestry clearcut area. Your script makes many of the dead end roads leading only to current or past clearcuts as unclassified, I think that is wrong.

Your script doesn't use track at all. I think that track should be used for smaller less important skogsbilvägar. This is not something I personally have come up with, this practice existed long before I started mapping in OSM. Yesterday I brought up the question in the swedish OSM facebook group and so far none has spoke up against that track should be used for these roads, but instead said that this is also how they map. One thing is that northern Sweden's type of huge network of forestry roads is quite uncommon in an international perspective.

That it should be track can also be deducted by exclusion, unclassified is not right due to the little importance of these roads in terms of getting to places, and service is not right either.

Your script makes all KLASS 9 roads to service, meaning that lots and lots of those minor skogsbilvägar becomes service. I think that is wrong, those should be track.

Then we have driveways and access roads to rural housing. My script will make these track, but they should be service. The reason these become track is that there is no data in the database to differ these from skogsbilvägar klass 9, both are enskild. One could do some geometry analysis in the script and take a guess (the driveways are often clustered together and are short often straight lines, while forestry roads are longer and turning and not clustered with others), however due to clustering in small area and using filters in JOSM I find manually changing these from track to service be quite easy task. There's also quite often a need to be more creative in villages, where parts of the roads should be unclassified, some track, some service, and if previously mapped there's usually more roads in the villages than in NVDB, usually driveways, but sometimes also tracks. Ie, manual changing driveways from track to service is a minor task seen to the whole.

As your script makes all KLASS 9 to service the driveways will be correctly marked as service, and instead one need to change all forestry roads and other minor non-service roads to track. I think the other way around is better as outlined above, I also think that if there are errors made, it's better that in this context of KLASS 9 roads a service road is marked as track than other way around.

(I've thought one idea to actually parse out from the raster map too to complement, there you can see where the houses are, and you have turning circles, and more road quality information, but it makes the processing much more complicated)

**Comment by NKAmapper** [comment]
I have added files named "_segment" in the example folder which contain the raw NVDB attributes (in Homogeniserad), which makes it easier to use the search function for looking at various tagging scenarios.

**Comment by NKAmapper** [comment]
Trunk/primary/secondary:
For trunk/primary/secondary, I still think it is a better to tag according to Vägkategori, because the importers will understand exactly what they are. They will have to be modified by the importer in any case. I noticed that you got the same feedback on Facebook some time ago. We could ask the community during the review, but I think then it would be good to show two files with each alternative, otherwise it gets a bit theoretical.

Tertiary:
For Göteborg, there is not one single tertiary despite having numerous streets at the 5/6 level. In Stockholm, there are only a handful of tertiary streets. Maybe there is a mistake somewhere. I think tertiary is a great way of showing the middle level arteries in cities. I used functional class 1-5 (which was not already trunk/primary/secondary), but I guess 6 would work as well.

Track:
* I have no strong views on how you tag forestry roads in Sweden (although it is a bit strange to deviate from the wiki). I am only looking for a practical approach: If the majority of a certain type/class roads are deemed to be track when importing, the file should use track as default. If the majority is service, the default should be service etc. Any alternative here will have a lot of "wrong" tagging, but the goal is to minimise it, I think. I am not tagging unclassified in a special way - the tagging is just a result of trying to chose the "majority" road class, which will be wrong in a number of cases.
* If you let class 8 be track, I would use unclassified for "Driftbidrag statligt/Vägnr", which all are leading to or connecting settlements. 
* Also, I had a look at "Tillgänglighetsklass" - tagging tilgängelighet class A and B as unclassified for roads with functional class 8 seems to make sense at Lycksele.
* A problem is more urban municipalities. I think Göteborg is going to look strange with functional class 8 and 9 as track (outside of urban area), and likely only right in 10% of cases. Perhaps the urban-to-rural ratio could be tested, and tracks then avoided for a low ratio.

**Comment by atorger** [comment]
Some tertiary gets residential tagging, as Gatutyp (vägkategori within cities) is parsed before KLASS. I'll look into adjusting that.

**Comment by atorger** [comment]
Driftbidrag works really well to upgrade track to unclassified in proper places, great tip. Added in that. I previously though driftbidrag was only used on larger roads so I had ignored that layer.

I looked at tillgänglighetsklass too, but to me it looks that it becomes many false positives, while driftbidrag solves the main problems.

About track on forestry road, there is actually an example of that on the track wiki page: "Example of a maintained asphalt forestry road, correctly tagged as highway=track + surface=asphalt + tracktype=grade1.". Indeed it's mainly intended for "tractor tracks" which not normal cars or hgv:s can go on, but the thing is that the wiki is written by people not familiar with Swedish forestry road network. The hgv:s that gets the timber are not special terrain vehicles, they are just regular hgv:s designed to run on regular roads, so that's the quality we have here. Anyway, I'm rather sure this is the way we should do it, ie they should be track, not service or unclassified, and we have good support from the community for that, and good support from existing mapping.

**Comment by atorger** [comment]
There's indeed a bug causing tertiaries etc to not show up inside cities. It's not so straightforward to solve due to difficulty to match current OSM mapping praxis with KLASS alone. Filed separate issue:
https://github.com/atorger/nvdb2osm/issues/19

**Comment by atorger** [comment]
You are correct that more urban municipalities without forestry road network get issues with track. I'll look into that issue, using Göteborg as test site.

**Comment by atorger** [comment]
Hmm....

Actually, there's a quite large highway type issue in the outer areas of urban municipalities, where you get outside "tätbebyggt område" according to NVDB, but actually still is in quite dense area.

Making them all track to service won't solve the problem here. Some of these should actually be residential, and some of the unclassified should also be residential. Quite many of these roads should be split, where one part is service, another part is track (I do that quite frequently in villages already up north). One can see that the raster map has better information on these roads than what is available in NVDB, where the road changes type in the middle while NVDB has just a single type.

I think we may have an unsolvable problem here, that is, regardless how we translate tags there will always be quite large amount of manual highway adjustment in these areas. Cities will be the last thing this script is used for though, as they are already quite well mapped, so it's more urgent to have good function in rural areas than in cities like Göteborg.

**Comment by atorger** [comment]
I've now tested the highway _link trick. Neat.

However, it is a bit "dangerous". What it does is subtracting FPV-KLASS from DoU-KLASS, and looking at what's left. It can only be used on roads that are included in FPV-klass, ie primary and up, and it trusts that DoU-KLASS includes links and that FPV-KLASS does not, so the difference = links.

I tested it on Malmö and it sort of works, but not quite. I'm hesitant to use it due to that it's just a side-effect how these layers happen to be delivered, rather than a layer actually pointing out links. It also is of limited value to include link tagging as ~100% of all these roads are already mapped, and 50+% will not match on highway type anyway so doing import there will mostly only be about refining geometry. A time saver for import is probably just to drop the highway tag (keep the others) and replace geometry to merge the rest.

So for now I won't include highway links in my translation..

**Comment by NKAmapper** [comment]
Track/service/residential in urban areas: It will never be perfect, and will require manual editing at import, but getting the default right for the majority of cases would be great. Many municipalities are semi-urban/semi-rural and will be import, I guess. Could a compromise be to have functional class 8 as service? Many of those will be wrong, of course, but may strike a better balance between urban/rural.

_link: It was correct in all the municipality which I tested. How bad were the mistakes? A few mistakes could be tolerated, I guess.

**Comment by atorger** [comment]
One could make a preset list depending on municipality and have different defaults depending on rural/urban, so say Lycksele has a different default than Göteborg, I can look into that later. However, if we are afraid that people are being lazy on roads that often need changes the best method would not to add the highway tag at all I think. While I need to analyze it more, I don't think there is a big difference in change-need if you make class 8 track or service in semi-urban areas, for rural areas with rich forestry road network (like Lycksele) track is better choice for our mapping tradition, in truly urban this distinction don't really appear so it doesn't matter. So semi-urban seems by far be the trickiest areas.

To make it significantly better in semi-urban I think one would need to scan additional information from the Lantmäteriet raster map (where buildings are, road type), which indeed is possible and I have thought about it, but quite complicated development project which I don't have the time to do now.

Yesterday I looked at various places on how Göteborg looks now in OSM, how it looks on aerials, how it looks on Lantmäteriet raster map, and what data we have in NVDB. From that using my experience of previous merging I thought about what I would keep from the current mapping, and what I would change. My conclusion is that semi-urban areas will be work-intensive regardless if you want to make a good job, and for the bigger city roads there's very little improvement to make.

Regarding links, there were not big mistakes, rather too few of them than too many, but a few differences from current mapping, and I don't really like using the DoU layer for something it's not intended for, it just happens that it includes links and FPV does not for now, nothing in the spec says that it should be that way. I also think there is very little value in adding *_link, big roads in big cities are already well mapped and it's better to put at the bottom of the fix list. Sometimes you end up with lots of work and test runs and adding smartness to the script for a very minor feature that won't be used much at all, and I think *_link is one of those.

I have added it it as a separate enhancement issue which one can look at later so we can focus on more important aspects for now: https://github.com/atorger/nvdb2osm/issues/20

It's better to spend effort on things like parsing out TrafikFörbud as good as possible, which is quite complicated with all conditionals.

**Comment by atorger** [comment]
I'm now about to look into a better guessing algorithm for service/track/unclassified, separate issue here: https://github.com/atorger/nvdb2osm/issues/24 so we can pause that discussion until I have something new to show.

**Comment by atorger** [comment]
I think all of the starting post issues have been addressed now.

**Comment by atorger** [comment]
Closing this issue, all should be fixed. If there are further improvements to make or more to discuss, open new issue.
