### ISSUE TITLE
new pipeline done, please check :)

### ISSUE THREAD

**Issue by matthiasfeist** [atorger/nvdb2osm#34]
Hi.

I have finished work on the new pipeline.
the UI is not as nice and I have removed the diff-map as it was not really working.

Please find the listing here: http://nvdb-osm-map-data.s3-website.eu-north-1.amazonaws.com/
There are some municipalities that for some reason can not be generated and I suspect you may want to look into them when you have time.

Thanks a lot!
Matthias

**Comment by matthiasfeist** [comment]
OK I just triggered a re-run of the pipeline. this will take quite a while so let's see tomorrow, what the status is

**Comment by atorger** [comment]
Most get through now, but a four fails still. I just fixed an issue (NVDB now can provide days for kollektivkörfält in enumerated format as well apparently) that should get us down to two. The last two on Stockholm and Mölndal are geometry issues which are usually a bit harder to fix, I'll see. I need to download and split some data locally. I have Stockholm already but it passes locally, so probably something has happened to the geometry in the latest NVDB data release, so I shall fetch the latest for these two and run to trigger the problem locally.

**Comment by atorger** [comment]
I've looked a bit at it now. Mölndal fails due to a real bug triggered by that a roundabout (circular way) is split in half as it is on the municipality border.

Stockholms fails due to some really bad mismatch between layers, the reference layer (RefLinjeTillkomst) and Funktionell Vägklass has different geometry for a few roads segments (RefLinjeTillkomst is the one that seems incorrect). Maybe I'll lay low with that and perhaps the source data is fixed, I'll see if I can report the error directly to Trafikverket. For the Mölndal issue I shall push a fix soon.

**Comment by atorger** [comment]
I've committed a fix for Mölndal, so it should work now. I've reported one Stockholm geometry error to Trafikverket, the other I found seems already fixed when viewed in the NVDB web interface, so I think we wait and see if the Stockholm geometry gets fixed instead of making some hack in the script to accept bad geometry.

**Comment by matthiasfeist** [comment]
Great. I am running the pipeline now, so we should see some results tomorrow.

**Comment by atorger** [comment]
Seems like Stockholm successfully completed too, so I guess the data error in NVDB has been corrected then in the latest dump. With all municipalities working now I close this issue.
