### ISSUE TITLE
Simplify cycleway crossings

### ISSUE THREAD

**Issue by atorger** [atorger/nvdb2osm#8]
NVDB maps cycleway crossings with roads as short way segments rather than just a node at the crossing. This is also legal in OSM and this is currently translated by the script. However, it's not a common way to map in OSM, and it does make cycleways inside cities very fragmented and thus leading to more work merging.

Maybe look into simplify this type of geometry and just node crossings instead.

**Comment by NKAmapper** [comment]
I have seen both methods used for mapping in OSM. Some users take care to tag the short crossing ways as highway=footway + footway=crossing (or similar for cycleway), while most users do not tag the crossing segment in any special way. I think your proposal is ok and in line with majority of mappers, i.e. no footway/cycleway=crossing on the way.

I would only add a _node_ at the intersection with highway=crossing if it is included from NVDB. Otherwise we would just be guessing what kind of crossing it is (markings etc). And it is not strictly necessary to add a crossing node each time a footway or cycleway crosses a (motor vehicle) highway.

**Comment by atorger** [comment]
This has now been implemented.
